<?php

namespace Database\Seeders;

use App\Models\Faskes;
use Illuminate\Database\Seeder;

class FinalFaskesSeeder extends Seeder
{
    public function run(): void
    {
        Faskes::truncate();

        $faskesData = [
            // ═══════════════════════════════════════════
            // RUMAH SAKIT (dari FasilitasKesehatanSeeder + Tambahan)
            // ═══════════════════════════════════════════
            [
                'name' => 'RSUD Sayang Cianjur',
                'type' => 'Rumah Sakit',
                'kecamatan' => 'Cianjur',
                'address' => 'Jl. Pasirgede Raya No.1B, Bojongherang, Kec. Cianjur, Kabupaten Cianjur, Jawa Barat 43216',
                'phone' => '(0263) 261026',
                'jam_operasional' => 'Senin - Minggu, 24 Jam (Gawat Darurat)',
                'lat' => -6.8106523,
                'lng' => 107.1411331,
                'layanan' => 'Rawat Inap',
                'akreditasi' => 'Paripurna',
            ],
            [
                'name' => 'RSUD Cimacan',
                'type' => 'Rumah Sakit',
                'kecamatan' => 'Pacet',
                'address' => 'Jl. Raya Cimacan No.17A, Palasari, Kec. Cipanas, Kabupaten Cianjur, Jawa Barat 43253',
                'phone' => '(0263) 512465',
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -6.7204843,
                'lng' => 107.0323843,
                'layanan' => 'Rawat Inap',
                'akreditasi' => 'Madya',
            ],
            [
                'name' => 'RS Bhayangkara Cianjur',
                'type' => 'Rumah Sakit',
                'kecamatan' => 'Cianjur',
                'address' => 'Jl. Suroso No.21, Solokpandan, Kec. Cianjur, Kabupaten Cianjur, Jawa Barat 43211',
                'phone' => null,
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -6.8190469,
                'lng' => 107.1406311,
                'layanan' => 'Rawat Inap',
                'akreditasi' => 'Madya',
            ],
            [
                'name' => 'RS Bersalin Al-Afiah',
                'type' => 'Rumah Sakit',
                'kecamatan' => 'Cianjur',
                'address' => 'Jl. Siti Jenab No.49, Pamoyanan, Kec. Cianjur, Kabupaten Cianjur, Jawa Barat 43211',
                'phone' => '(0263) 261027',
                'jam_operasional' => 'Senin - Sabtu, 08.00 - 20.00',
                'lat' => -6.8212161,
                'lng' => 107.1382625,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'RS Dr. Hafiz (RSDH) Cianjur',
                'type' => 'Rumah Sakit',
                'kecamatan' => 'Karangtengah',
                'address' => 'Jl. Pramuka No.15, Bojong, Kec. Karangtengah, Kabupaten Cianjur, Jawa Barat 43281',
                'phone' => '(0263) 2910000',
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -6.7980975,
                'lng' => 107.1753116,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'RS Edelweiss Bentang Salapan',
                'type' => 'Rumah Sakit',
                'kecamatan' => 'Karangtengah',
                'address' => 'Jl. Nasional III No.253-254, Bojong, Kec. Karangtengah, Kabupaten Cianjur, Jawa Barat 43281',
                'phone' => '(0263) 5600999',
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -6.8031379,
                'lng' => 107.1715779,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'RS Hermina CMS Cianjur',
                'type' => 'Rumah Sakit',
                'kecamatan' => 'Cianjur',
                'address' => 'Nagrak, Kec. Cianjur, Kabupaten Cianjur, Jawa Barat 43215',
                'phone' => null,
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -6.834112,
                'lng' => 107.1232456,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],

            // ═══════════════════════════════════════════
            // PUSKESMAS (dari FasilitasKesehatanSeeder)
            // ═══════════════════════════════════════════
            [
                'name' => 'Puskesmas Cianjur Kota',
                'type' => 'Puskesmas',
                'kecamatan' => 'Cianjur',
                'address' => 'Jl. Surya Kencana, Sawah Gede, Kec. Cianjur, Kabupaten Cianjur, Jawa Barat 43212',
                'phone' => '0812-9011-7250',
                'jam_operasional' => 'Senin - Kamis 07.30-16.00, Jumat 07.30-11.00, Sabtu 07.30-11.30',
                'lat' => -6.8248895,
                'lng' => 107.1325669,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => 'Madya',
            ],
            [
                'name' => 'Puskesmas Cugenang',
                'type' => 'Puskesmas',
                'kecamatan' => 'Cugenang',
                'address' => 'Mangunkerta, Kec. Cugenang, Kabupaten Cianjur, Jawa Barat 43252',
                'phone' => null,
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -6.8019797,
                'lng' => 107.0615198,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Pacet',
                'type' => 'Puskesmas',
                'kecamatan' => 'Pacet',
                'address' => 'Jl. Wijaya Kusuma, Cipendawa, Kec. Pacet, Kabupaten Cianjur, Jawa Barat 43253',
                'phone' => '(0263) 512135',
                'jam_operasional' => 'Senin - Kamis 08.00-12.00, Jumat 08.00-11.00, Sabtu 08.00-12.00',
                'lat' => -6.7493404,
                'lng' => 107.0482877,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas DTP Sukaresmi',
                'type' => 'Puskesmas',
                'kecamatan' => 'Sukaresmi',
                'address' => 'Jl. Mariwati, Kawungluwuk, Kec. Sukaresmi, Kabupaten Cianjur, Jawa Barat 43254',
                'phone' => '0819-1205-5261',
                'jam_operasional' => 'Setiap Hari',
                'lat' => -6.724819,
                'lng' => 107.077797,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'UPTD Puskesmas DTP Cikalongkulon',
                'type' => 'Puskesmas',
                'kecamatan' => 'Cikalongkulon',
                'address' => 'Jl. Aria Wiratanudatar, Sukagalih, Kec. Cikalongkulon, Kabupaten Cianjur, Jawa Barat 43291',
                'phone' => '(0263) 317026',
                'jam_operasional' => 'Senin - Sabtu, 08.00 - 14.00',
                'lat' => -6.7133521,
                'lng' => 107.2123843,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas DTP Mande',
                'type' => 'Puskesmas',
                'kecamatan' => 'Mande',
                'address' => 'Jl. Raya Jamali, Kec. Mande, Kabupaten Cianjur, Jawa Barat 43292',
                'phone' => null,
                'jam_operasional' => 'Setiap Hari',
                'lat' => -6.7545261,
                'lng' => 107.1970516,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Karangtengah',
                'type' => 'Puskesmas',
                'kecamatan' => 'Karangtengah',
                'address' => 'Jl. Raya Bandung-Karangtengah KM.4, Sabandar, Kec. Karangtengah, Kabupaten Cianjur, Jawa Barat 43215',
                'phone' => '(0263) 2912031',
                'jam_operasional' => 'Senin - Kamis 08.00-14.00, Jumat 08.00-12.00, Sabtu 08.00-13.00',
                'lat' => -6.8044885,
                'lng' => 107.1674302,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Sukaluyu',
                'type' => 'Puskesmas',
                'kecamatan' => 'Sukaluyu',
                'address' => 'Sukamulya, Kec. Sukaluyu, Kabupaten Cianjur, Jawa Barat 43284',
                'phone' => null,
                'jam_operasional' => 'Senin - Sabtu, 08.00 - 14.00',
                'lat' => -6.8432866,
                'lng' => 107.2221095,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Rawat Inap Ciranjang',
                'type' => 'Puskesmas',
                'kecamatan' => 'Ciranjang',
                'address' => 'Jl. Rumah Sakit No.194, Ciranjang, Kec. Ciranjang, Kabupaten Cianjur, Jawa Barat 43282',
                'phone' => '(0263) 322306',
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -6.8140912,
                'lng' => 107.2443287,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Bojongpicung',
                'type' => 'Puskesmas',
                'kecamatan' => 'Bojongpicung',
                'address' => 'Jl. Pasir Angin, Neglasari, Kec. Bojongpicung, Kabupaten Cianjur, Jawa Barat 43283',
                'phone' => '(0263) 322353',
                'jam_operasional' => 'Senin - Sabtu, 08.00 - 14.00',
                'lat' => -6.8452647,
                'lng' => 107.2710507,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Haurwangi',
                'type' => 'Puskesmas',
                'kecamatan' => 'Haurwangi',
                'address' => 'Jl. Raya Bandung, Kertamukti, Kec. Haurwangi, Kabupaten Cianjur, Jawa Barat 43283',
                'phone' => '0851-7114-4169',
                'jam_operasional' => 'Senin - Kamis 07.30-14.00, Jumat 07.30-11.00, Sabtu 07.30-13.00',
                'lat' => -6.810805,
                'lng' => 107.2944183,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Warungkondang',
                'type' => 'Puskesmas',
                'kecamatan' => 'Warungkondang',
                'address' => 'Jl. Jambudipa No.43, Jambudipa, Kec. Warungkondang, Kabupaten Cianjur, Jawa Barat 43261',
                'phone' => '(0263) 272273',
                'jam_operasional' => 'Senin - Jumat 07.00-16.00, Sabtu 07.00-12.00',
                'lat' => -6.8694783,
                'lng' => 107.0944027,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'UPTD Puskesmas Gekbrong',
                'type' => 'Puskesmas',
                'kecamatan' => 'Gekbrong',
                'address' => 'Jl. Raya Sukabumi - Cianjur KM.15, Gekbrong, Kec. Gekbrong, Kabupaten Cianjur, Jawa Barat 43261',
                'phone' => '(0266) 260422',
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -6.8680746,
                'lng' => 107.0372163,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Cibeber',
                'type' => 'Puskesmas',
                'kecamatan' => 'Cibeber',
                'address' => 'Jl. Raya Cibeber KM.9 No.14, Sukasari, Kec. Cibeber, Kabupaten Cianjur, Jawa Barat 43262',
                'phone' => '(0263) 334244',
                'jam_operasional' => 'Senin - Kamis 07.00-15.00, Jumat 07.00-11.00, Sabtu 07.00-14.00',
                'lat' => -6.8843912,
                'lng' => 107.1262108,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'PHC UPTD Campaka',
                'type' => 'Puskesmas',
                'kecamatan' => 'Campaka',
                'address' => 'Jl. Arah Curug Malela, Sukajadi, Kec. Campaka, Kabupaten Cianjur, Jawa Barat 43263',
                'phone' => '(0263) 341222',
                'jam_operasional' => 'Senin - Kamis 07.30-12.00, Jumat-Sabtu 07.30-10.00',
                'lat' => -6.9983167,
                'lng' => 107.142395,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Campaka Mulya',
                'type' => 'Puskesmas',
                'kecamatan' => 'Campakamulya',
                'address' => 'Campakamulya, Kec. Campaka Mulya, Kabupaten Cianjur, Jawa Barat 43269',
                'phone' => null,
                'jam_operasional' => 'Senin - Sabtu, 08.00 - 14.00',
                'lat' => -7.0784888,
                'lng' => 107.1706673,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Cijati',
                'type' => 'Puskesmas',
                'kecamatan' => 'Cijati',
                'address' => 'Cijati, Kec. Cijati, Kabupaten Cianjur, Jawa Barat 43284',
                'phone' => null,
                'jam_operasional' => 'Senin - Kamis 08.00-16.00, Jumat 08.00-11.00, Sabtu 08.00-13.00',
                'lat' => -7.2605655,
                'lng' => 107.033487,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas DTP Sukanagara',
                'type' => 'Puskesmas',
                'kecamatan' => 'Sukanagara',
                'address' => 'Jl. Raya Sukanagara KM.2, Kec. Sukanagara, Kabupaten Cianjur, Jawa Barat 43264',
                'phone' => null,
                'jam_operasional' => 'Senin - Sabtu, 24 Jam',
                'lat' => -7.0936314,
                'lng' => 107.1335623,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Poned Takokak',
                'type' => 'Puskesmas',
                'kecamatan' => 'Takokak',
                'address' => 'Jl. Pasanggrahan, Pasawahan, Kec. Takokak, Kabupaten Cianjur, Jawa Barat 43265',
                'phone' => null,
                'jam_operasional' => 'Senin - Sabtu, 08.00 - 14.00',
                'lat' => -7.049478,
                'lng' => 107.0042047,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Kadupandak',
                'type' => 'Puskesmas',
                'kecamatan' => 'Kadupandak',
                'address' => 'Jl. Karamat No.1, Kadupandak, Kabupaten Cianjur, Jawa Barat 43268',
                'phone' => null,
                'jam_operasional' => 'Senin - Sabtu, 07.30 - 12.00',
                'lat' => -7.2587806,
                'lng' => 107.0477087,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Pagelaran',
                'type' => 'Puskesmas',
                'kecamatan' => 'Pagelaran',
                'address' => 'Buniwangi, Kec. Pagelaran, Kabupaten Cianjur, Jawa Barat 43266',
                'phone' => null,
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -7.1863258,
                'lng' => 107.1534527,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Tanggeung',
                'type' => 'Puskesmas',
                'kecamatan' => 'Tanggeung',
                'address' => 'Jl. Pasarkolot, Kertajaya, Kec. Tanggeung, Kabupaten Cianjur, Jawa Barat 43267',
                'phone' => null,
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -7.2705087,
                'lng' => 107.1305825,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Pasirkuda',
                'type' => 'Puskesmas',
                'kecamatan' => 'Pasirkuda',
                'address' => 'Kalibaru, Kec. Pasirkuda, Kabupaten Cianjur, Jawa Barat 43266',
                'phone' => null,
                'jam_operasional' => 'Senin - Sabtu, 08.00 - 14.00',
                'lat' => -7.2123348,
                'lng' => 107.1959478,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Cibinong',
                'type' => 'Puskesmas',
                'kecamatan' => 'Cibinong',
                'address' => 'Sukajadi, Kec. Cibinong, Kabupaten Cianjur, Jawa Barat 43271',
                'phone' => null,
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -7.3176944,
                'lng' => 107.1276769,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Rawat Inap Cidaun',
                'type' => 'Puskesmas',
                'kecamatan' => 'Cidaun',
                'address' => 'Jl. Pelabuhan Jayanti No.21, Cidamar, Kec. Cidaun, Kabupaten Cianjur, Jawa Barat 43275',
                'phone' => null,
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -7.4913571,
                'lng' => 107.3616561,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Sindangbarang',
                'type' => 'Puskesmas',
                'kecamatan' => 'Sindangbarang',
                'address' => 'Saganten, Kec. Sindangbarang, Kabupaten Cianjur, Jawa Barat 43272',
                'phone' => null,
                'jam_operasional' => 'Senin - Minggu, 24 Jam',
                'lat' => -7.4533037,
                'lng' => 107.1414776,
                'layanan' => 'Rawat Inap',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Agrabinta',
                'type' => 'Puskesmas',
                'kecamatan' => 'Agrabinta',
                'address' => 'Jl. Raya Agrabinta, Bojongkaso, Kec. Agrabinta, Kabupaten Cianjur, Jawa Barat 43273',
                'phone' => '0857-9304-3279',
                'jam_operasional' => 'Senin - Minggu, 07.30 - 15.00',
                'lat' => -7.416762,
                'lng' => 106.8995552,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
            [
                'name' => 'Puskesmas Leles',
                'type' => 'Puskesmas',
                'kecamatan' => 'Leles',
                'address' => 'Pusakasari, Kec. Leles, Kabupaten Cianjur, Jawa Barat 43273',
                'phone' => null,
                'jam_operasional' => 'Senin - Kamis 08.00-12.00, Jumat 08.00-11.00',
                'lat' => -7.3714988,
                'lng' => 106.9831577,
                'layanan' => 'Rawat Jalan',
                'akreditasi' => null,
            ],
        ];

        foreach ($faskesData as $data) {
            Faskes::create($data);
        }

        $this->command->info(count($faskesData).' faskes berhasil di-seed!');
    }
}
